// Each widget registers itself on import; importing this module is what makes
// them available.
import './greeting/GreetingWidget'
import './clock/ClockWidget'
import './weather/WeatherWidget'
import './continue/ContinueWidget'
import './calendar/CalendarWidget'
import './notes/NotesWidget'
import './todo/TodoWidget'
import './timer/TimerWidget'
import './browser/TopSitesWidget'
import './browser/TabsWidget'
import './browser/BookmarksWidget'
import './browser/HistoryWidget'
import './browser/DownloadsWidget'
import './feed/FeedWidget'
import './crypto/CryptoWidget'
import './llm/ClaudeUsageWidget'
import './llm/ChatGPTUsageWidget'
import './spotify/SpotifyWidget'

export { WidgetCanvas } from './WidgetCanvas'
