/**
 * Curated domain -> Simple Icons slug map.
 *
 * A speed dial holds a few dozen well-known sites, so shipping every one of the
 * 3,400 Simple Icons (~2MB of path data) would be waste. This list covers the
 * sites people actually pin; anything else falls back to Chrome's own favicon
 * cache, a monogram, or an image the user supplies.
 *
 * `null` means "derive the slug from the first domain label".
 */
export const brandDomains = {
  // search, mail, productivity
  'google.com': 'google',
  'mail.google.com': 'gmail',
  'gmail.com': 'gmail',
  'drive.google.com': 'googledrive',
  'docs.google.com': 'googledocs',
  'sheets.google.com': 'googlesheets',
  'slides.google.com': 'googleslides',
  'meet.google.com': 'googlemeet',
  'calendar.google.com': 'googlecalendar',
  'photos.google.com': 'googlephotos',
  'keep.google.com': 'googlekeep',
  'translate.google.com': 'googletranslate',
  'maps.google.com': 'googlemaps',
  'news.google.com': 'googlenews',
  'console.cloud.google.com': 'googlecloud',
  'cloud.google.com': 'googlecloud',
  'analytics.google.com': 'googleanalytics',
  'search.google.com': 'google',
  'duckduckgo.com': 'duckduckgo',
  'ecosia.org': 'ecosia',
  'startpage.com': 'startpage',
  'brave.com': 'brave',
  'search.brave.com': 'brave',
  'perplexity.ai': 'perplexity',
  'kagi.com': 'kagi',
  'baidu.com': 'baidu',
  'proton.me': 'proton',
  'mail.proton.me': 'protonmail',
  'zoho.com': 'zoho',
  'notion.so': 'notion',
  'notion.com': 'notion',
  'obsidian.md': 'obsidian',
  'evernote.com': 'evernote',
  'todoist.com': 'todoist',
  'trello.com': 'trello',
  'asana.com': 'asana',
  'clickup.com': 'clickup',
  'linear.app': 'linear',
  'basecamp.com': 'basecamp',
  'airtable.com': 'airtable',
  'miro.com': 'miro',
  'figma.com': 'figma',
  'dropbox.com': 'dropbox',
  'box.com': 'box',
  'zoom.us': 'zoom',
  'calendly.com': 'calendly',
  'grammarly.com': 'grammarly',
  'lastpass.com': 'lastpass',
  '1password.com': '1password',
  'bitwarden.com': 'bitwarden',

  // ai
  'claude.ai': 'claude',
  'anthropic.com': 'anthropic',
  'console.anthropic.com': 'anthropic',
  'gemini.google.com': 'googlegemini',
  'aistudio.google.com': 'googlegemini',
  'copilot.microsoft.com': 'githubcopilot',
  'huggingface.co': 'huggingface',
  'replicate.com': 'replicate',
  'ollama.com': 'ollama',
  'mistral.ai': 'mistralai',
  'v0.dev': 'v0',
  'cursor.com': 'cursor',
  'deepseek.com': 'deepseek',

  // dev
  'github.com': 'github',
  'gist.github.com': 'github',
  'gitlab.com': 'gitlab',
  'bitbucket.org': 'bitbucket',
  'stackoverflow.com': 'stackoverflow',
  'stackexchange.com': 'stackexchange',
  'npmjs.com': 'npm',
  'pypi.org': 'pypi',
  'crates.io': 'rust',
  'developer.mozilla.org': 'mdnwebdocs',
  'vercel.com': 'vercel',
  'netlify.com': 'netlify',
  'railway.app': 'railway',
  'render.com': 'render',
  'fly.io': 'flydotio',
  'cloudflare.com': 'cloudflare',
  'dash.cloudflare.com': 'cloudflare',
  'digitalocean.com': 'digitalocean',
  'supabase.com': 'supabase',
  'firebase.google.com': 'firebase',
  'console.firebase.google.com': 'firebase',
  'planetscale.com': 'planetscale',
  'mongodb.com': 'mongodb',
  'redis.io': 'redis',
  'postgresql.org': 'postgresql',
  'docker.com': 'docker',
  'hub.docker.com': 'docker',
  'kubernetes.io': 'kubernetes',
  'terraform.io': 'terraform',
  'jenkins.io': 'jenkins',
  'circleci.com': 'circleci',
  'sentry.io': 'sentry',
  'datadoghq.com': 'datadog',
  'grafana.com': 'grafana',
  'postman.com': 'postman',
  'insomnia.rest': 'insomnia',
  'leetcode.com': 'leetcode',
  'hackerrank.com': 'hackerrank',
  'codeforces.com': 'codeforces',
  'codechef.com': 'codechef',
  'exercism.org': 'exercism',
  'codesandbox.io': 'codesandbox',
  'stackblitz.com': 'stackblitz',
  'replit.com': 'replit',
  'jsfiddle.net': 'jsfiddle',
  'dev.to': 'devdotto',
  'hashnode.com': 'hashnode',
  'medium.com': 'medium',
  'substack.com': 'substack',
  'news.ycombinator.com': 'ycombinator',
  'producthunt.com': 'producthunt',
  'jira.atlassian.com': 'jira',
  'atlassian.net': 'jira',
  'confluence.atlassian.com': 'confluence',
  'sourceforge.net': 'sourceforge',
  'arxiv.org': 'arxiv',
  'kaggle.com': 'kaggle',
  'colab.research.google.com': 'googlecolab',
  'jupyter.org': 'jupyter',
  'anaconda.com': 'anaconda',

  // social
  'x.com': 'x',
  'twitter.com': 'x',
  'reddit.com': 'reddit',
  'facebook.com': 'facebook',
  'instagram.com': 'instagram',
  'threads.net': 'threads',
  'bsky.app': 'bluesky',
  'mastodon.social': 'mastodon',
  'tiktok.com': 'tiktok',
  'pinterest.com': 'pinterest',
  'snapchat.com': 'snapchat',
  'tumblr.com': 'tumblr',
  'quora.com': 'quora',
  'discord.com': 'discord',
  'telegram.org': 'telegram',
  'web.telegram.org': 'telegram',
  'web.whatsapp.com': 'whatsapp',
  'whatsapp.com': 'whatsapp',
  'signal.org': 'signal',
  'messenger.com': 'messenger',
  'meetup.com': 'meetup',
  'nextdoor.com': 'nextdoor',
  'wechat.com': 'wechat',
  'line.me': 'line',
  'vk.com': 'vk',
  'weibo.com': 'sinaweibo',

  // video, music, media
  'youtube.com': 'youtube',
  'music.youtube.com': 'youtubemusic',
  'studio.youtube.com': 'youtubestudio',
  'netflix.com': 'netflix',
  'max.com': 'hbo',
  'paramountplus.com': 'paramountplus',
  'appletv.com': 'appletv',
  'tv.apple.com': 'appletv',
  'crunchyroll.com': 'crunchyroll',
  'twitch.tv': 'twitch',
  'vimeo.com': 'vimeo',
  'dailymotion.com': 'dailymotion',
  'plex.tv': 'plex',
  'jellyfin.org': 'jellyfin',
  'spotify.com': 'spotify',
  'open.spotify.com': 'spotify',
  'music.apple.com': 'applemusic',
  'soundcloud.com': 'soundcloud',
  'bandcamp.com': 'bandcamp',
  'tidal.com': 'tidal',
  'deezer.com': 'deezer',
  'last.fm': 'lastdotfm',
  'audible.com': 'audible',
  'imdb.com': 'imdb',
  'letterboxd.com': 'letterboxd',
  'rottentomatoes.com': 'rottentomatoes',
  'goodreads.com': 'goodreads',
  'podcasts.apple.com': 'applepodcasts',

  // shopping, finance, travel
  'ebay.com': 'ebay',
  'etsy.com': 'etsy',
  'aliexpress.com': 'aliexpress',
  'target.com': 'target',
  'ikea.com': 'ikea',
  'shopify.com': 'shopify',
  'zomato.com': 'zomato',
  'swiggy.com': 'swiggy',
  'bigbasket.com': 'bigbasket',
  'paytm.com': 'paytm',
  'phonepe.com': 'phonepe',
  'razorpay.com': 'razorpay',
  'zerodha.com': 'zerodha',
  'paypal.com': 'paypal',
  'stripe.com': 'stripe',
  'wise.com': 'wise',
  'revolut.com': 'revolut',
  'chase.com': 'chase',
  'coinbase.com': 'coinbase',
  'binance.com': 'binance',
  'robinhood.com': 'robinhood',
  'tradingview.com': 'tradingview',
  'booking.com': 'bookingdotcom',
  'airbnb.com': 'airbnb',
  'expedia.com': 'expedia',
  'tripadvisor.com': 'tripadvisor',
  'uber.com': 'uber',
  'lyft.com': 'lyft',

  // news, reference, learning
  'wikipedia.org': 'wikipedia',
  'en.wikipedia.org': 'wikipedia',
  'cnn.com': 'cnn',
  'theguardian.com': 'theguardian',
  'nba.com': 'nba',
  'fifa.com': 'fifa',
  'coursera.org': 'coursera',
  'udemy.com': 'udemy',
  'edx.org': 'edx',
  'khanacademy.org': 'khanacademy',
  'duolingo.com': 'duolingo',
  'pluralsight.com': 'pluralsight',
  'skillshare.com': 'skillshare',
  'freecodecamp.org': 'freecodecamp',
  'scholar.google.com': 'googlescholar',
  'researchgate.net': 'researchgate',
  'archive.org': 'internetarchive',
  'overleaf.com': 'overleaf',

  // gaming, misc
  'store.steampowered.com': 'steam',
  'steampowered.com': 'steam',
  'epicgames.com': 'epicgames',
  'itch.io': 'itchdotio',
  'chess.com': 'chessdotcom',
  'lichess.org': 'lichess',
  'roblox.com': 'roblox',
  'playstation.com': 'playstation',
  'gog.com': 'gogdotcom',
  'unsplash.com': 'unsplash',
  'pexels.com': 'pexels',
  'behance.net': 'behance',
  'dribbble.com': 'dribbble',
  'flickr.com': 'flickr',
  'deviantart.com': 'deviantart',
  'apple.com': 'apple',
  'icloud.com': 'icloud',
  'samsung.com': 'samsung',
  'nvidia.com': 'nvidia',
  'tesla.com': 'tesla',
  'speedtest.net': 'speedtest',
  'wetransfer.com': 'wetransfer',
  'feedly.com': 'feedly',
  'ifttt.com': 'ifttt',
  'zapier.com': 'zapier',
  'homeassistant.io': 'homeassistant',
  'home-assistant.io': 'homeassistant',
  'protonvpn.com': 'protonvpn',
  'nordvpn.com': 'nordvpn',
  'tailscale.com': 'tailscale',
}

/**
 * Hosts whose brand was removed from Simple Icons upstream (the project drops
 * logos without a permissive licence). For these the tile falls back to the
 * site's own favicon rendered large on a plate tinted from that favicon -
 * which is what every uncurated site gets too, and looks close to identical.
 */
export const unavailableBrands = [
  'bing.com',
  'yandex.com',
  'outlook.com',
  'outlook.live.com',
  'outlook.office.com',
  'office.com',
  'microsoft.com',
  'teams.microsoft.com',
  'onedrive.live.com',
  'sharepoint.com',
  'fastmail.com',
  'monday.com',
  'canva.com',
  'chatgpt.com',
  'chat.openai.com',
  'openai.com',
  'platform.openai.com',
  'midjourney.com',
  'grok.com',
  'heroku.com',
  'aws.amazon.com',
  'console.aws.amazon.com',
  'portal.azure.com',
  'azure.microsoft.com',
  'codepen.io',
  'devdocs.io',
  'linkedin.com',
  'slack.com',
  'primevideo.com',
  'hotstar.com',
  'jiocinema.com',
  'disneyplus.com',
  'hulu.com',
  'peacocktv.com',
  'amazon.com',
  'amazon.in',
  'amazon.co.uk',
  'alibaba.com',
  'walmart.com',
  'costco.com',
  'bestbuy.com',
  'flipkart.com',
  'myntra.com',
  'blinkit.com',
  'zepto.com',
  'groww.in',
  'kraken.com',
  'finance.yahoo.com',
  'bloomberg.com',
  'wsj.com',
  'ft.com',
  'olacabs.com',
  'irctc.co.in',
  'makemytrip.com',
  'skyscanner.net',
  'kayak.com',
  'bbc.com',
  'bbc.co.uk',
  'nytimes.com',
  'reuters.com',
  'apnews.com',
  'aljazeera.com',
  'espn.com',
  'cricbuzz.com',
  'brilliant.org',
  'jstor.org',
  'wolframalpha.com',
  'desmos.com',
  'minecraft.net',
  'xbox.com',
  'nintendo.com',
  'raindrop.io',
  'pocket.com',
  'getpocket.com',
]
