/**
 * The one place Font Awesome is imported.
 *
 * Every icon in the app is referenced by a key from this map. That keeps the
 * bundle tree-shaken to icons we actually use, gives settings a stable string
 * to persist, and makes the "Font Awesome only, no emoji or ad-hoc glyphs" rule
 * enforceable by lint (see `eslint.config.js`).
 */
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowRightFromBracket,
  faArrowRotateLeft,
  faArrowUpRightFromSquare,
  faBars,
  faBolt,
  faBookmark,
  faBoxArchive,
  faBriefcase,
  faBrush,
  faCalculator,
  faCalendarDays,
  faCaretDown,
  faChartLine,
  faCheck,
  faCheckDouble,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleHalfStroke,
  faCircleInfo,
  faCircleNodes,
  faClock,
  faClockRotateLeft,
  faClone,
  faCloud,
  faCloudArrowDown,
  faCloudArrowUp,
  faCloudBolt,
  faCloudMoon,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudSun,
  faCode,
  faCompress,
  faCopy,
  faDesktop,
  faDroplet,
  faEllipsis,
  faEye,
  faEyeSlash,
  faFileExport,
  faFileImport,
  faFilm,
  faFire,
  faFolderOpen,
  faFont,
  faGear,
  faGlobe,
  faGrip,
  faHourglassHalf,
  faHouse,
  faImage,
  faKeyboard,
  faLayerGroup,
  faLink,
  faListCheck,
  faLocationDot,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMoon,
  faNoteSticky,
  faPalette,
  faPause,
  faPen,
  faPlay,
  faPlus,
  faRotate,
  faSliders,
  faSmog,
  faSnowflake,
  faSpinner,
  faSquare,
  faStar,
  faStop,
  faSun,
  faTableCellsLarge,
  faTemperatureHalf,
  faThumbTack,
  faToggleOff,
  faToggleOn,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faWandMagicSparkles,
  faWind,
  faWindowMaximize,
  faWindowRestore,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { faCircle, faSquare as faSquareOutline } from '@fortawesome/free-regular-svg-icons'
import {
  faChrome,
  faGithub,
  faGoogle,
  faWikipediaW,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'

export const icons = {
  /* actions */
  add: faPlus,
  close: faXmark,
  check: faCheck,
  checkAll: faCheckDouble,
  edit: faPen,
  remove: faTrash,
  copy: faCopy,
  duplicate: faClone,
  more: faEllipsis,
  drag: faGrip,
  reset: faArrowRotateLeft,
  refresh: faRotate,
  upload: faUpload,
  external: faArrowUpRightFromSquare,
  open: faArrowRightFromBracket,
  pin: faThumbTack,
  lock: faLock,
  unlock: faLockOpen,
  play: faPlay,
  pause: faPause,
  stop: faStop,
  spinner: faSpinner,
  collapse: faCompress,
  menu: faBars,

  /* chevrons */
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  caretDown: faCaretDown,

  /* settings + theme */
  settings: faGear,
  sliders: faSliders,
  palette: faPalette,
  brush: faBrush,
  font: faFont,
  shape: faSquare,
  shapeOutline: faSquareOutline,
  circle: faCircle,
  light: faSun,
  dark: faMoon,
  auto: faCircleHalfStroke,
  layout: faTableCellsLarge,
  layers: faLayerGroup,
  magic: faWandMagicSparkles,
  toggleOn: faToggleOn,
  toggleOff: faToggleOff,
  keyboard: faKeyboard,
  info: faCircleInfo,
  warning: faTriangleExclamation,
  show: faEye,
  hide: faEyeSlash,
  export: faFileExport,
  import: faFileImport,

  /* content */
  search: faMagnifyingGlass,
  clock: faClock,
  history: faClockRotateLeft,
  calendar: faCalendarDays,
  bookmark: faBookmark,
  folder: faFolderOpen,
  download: faCloudArrowDown,
  upstream: faCloudArrowUp,
  notes: faNoteSticky,
  todo: faListCheck,
  tabs: faWindowRestore,
  window: faWindowMaximize,
  desktop: faDesktop,
  link: faLink,
  globe: faGlobe,
  image: faImage,
  video: faFilm,
  timer: faHourglassHalf,
  stocks: faChartLine,
  calculator: faCalculator,
  archive: faBoxArchive,
  star: faStar,
  home: faHouse,
  work: faBriefcase,
  code: faCode,
  network: faCircleNodes,
  bolt: faBolt,
  location: faLocationDot,

  /* weather */
  weather: faCloud,
  weatherClear: faSun,
  weatherClearNight: faMoon,
  weatherPartly: faCloudSun,
  weatherPartlyNight: faCloudMoon,
  weatherRain: faCloudRain,
  weatherHeavyRain: faCloudShowersHeavy,
  weatherStorm: faCloudBolt,
  weatherSnow: faSnowflake,
  weatherFog: faSmog,
  wind: faWind,
  humidity: faDroplet,
  temperature: faTemperatureHalf,
  hot: faFire,

  /* brands (search engines and known services only) */
  brandGoogle: faGoogle,
  brandYoutube: faYoutube,
  brandGithub: faGithub,
  brandWikipedia: faWikipediaW,
  brandChrome: faChrome,
} satisfies Record<string, IconDefinition>

export type IconName = keyof typeof icons

export const iconNames = Object.keys(icons) as IconName[]
