/**
 * The one place Font Awesome is imported.
 *
 * Every icon in the app is referenced by a key from this map. That keeps the
 * bundle tree-shaken to icons actually in use, gives settings a stable string to
 * persist, and makes the "Font Awesome only, no emoji or ad-hoc glyphs" rule
 * enforceable by lint (see `eslint.config.js`).
 *
 * Keep this pruned: unused entries are dead weight on a page whose whole job is
 * to paint instantly. `npm run icons:check` reports anything unreferenced.
 */
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowRightFromBracket,
  faArrowRotateLeft,
  faBoxArchive,
  faArrowUpRightFromSquare,
  faBookmark,
  faCalculator,
  faCalendarDays,
  faCaretDown,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleHalfStroke,
  faCircleInfo,
  faCircleNodes,
  faClock,
  faClockRotateLeft,
  faClone,
  faCloud,
  faCloudArrowDown,
  faCloudArrowUp,
  faCloudBolt,
  faCloudMoon,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudSun,
  faCopy,
  faDroplet,
  faEyeSlash,
  faFileExport,
  faFileImport,
  faFilm,
  faFolderOpen,
  faFont,
  faGear,
  faHourglassHalf,
  faGrip,
  faImage,
  faKeyboard,
  faLayerGroup,
  faLink,
  faListCheck,
  faLocationDot,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMoon,
  faNoteSticky,
  faPalette,
  faPause,
  faPen,
  faPlay,
  faPlus,
  faSliders,
  faSmog,
  faSnowflake,
  faSpinner,
  faSquare,
  faStar,
  faSun,
  faTableCellsLarge,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faWandMagicSparkles,
  faWind,
  faWindowMaximize,
  faWindowRestore,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { faChrome } from '@fortawesome/free-brands-svg-icons'

export const icons = {
  add: faPlus,
  close: faXmark,
  check: faCheck,
  edit: faPen,
  open: faArrowRightFromBracket,
  remove: faTrash,
  copy: faCopy,
  duplicate: faClone,
  drag: faGrip,
  reset: faArrowRotateLeft,
  upload: faUpload,
  external: faArrowUpRightFromSquare,
  lock: faLock,
  unlock: faLockOpen,
  spinner: faSpinner,
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  caretDown: faCaretDown,
  settings: faGear,
  sliders: faSliders,
  palette: faPalette,
  font: faFont,
  shape: faSquare,
  light: faSun,
  dark: faMoon,
  auto: faCircleHalfStroke,
  layout: faTableCellsLarge,
  layers: faLayerGroup,
  magic: faWandMagicSparkles,
  keyboard: faKeyboard,
  info: faCircleInfo,
  warning: faTriangleExclamation,
  hide: faEyeSlash,
  export: faFileExport,
  import: faFileImport,
  search: faMagnifyingGlass,
  stocks: faChartLine,
  clock: faClock,
  timer: faHourglassHalf,
  play: faPlay,
  pause: faPause,
  history: faClockRotateLeft,
  calendar: faCalendarDays,
  archive: faBoxArchive,
  bookmark: faBookmark,
  folder: faFolderOpen,
  download: faCloudArrowDown,
  upstream: faCloudArrowUp,
  feed: faCircleNodes,
  notes: faNoteSticky,
  todo: faListCheck,
  tabs: faWindowRestore,
  window: faWindowMaximize,
  link: faLink,
  image: faImage,
  video: faFilm,
  calculator: faCalculator,
  star: faStar,
  location: faLocationDot,
  weather: faCloud,
  weatherClear: faSun,
  weatherClearNight: faMoon,
  weatherPartly: faCloudSun,
  weatherPartlyNight: faCloudMoon,
  weatherRain: faCloudRain,
  weatherHeavyRain: faCloudShowersHeavy,
  weatherStorm: faCloudBolt,
  weatherSnow: faSnowflake,
  weatherFog: faSmog,
  wind: faWind,
  humidity: faDroplet,
  brandChrome: faChrome,
} satisfies Record<string, IconDefinition>

export type IconName = keyof typeof icons

export const iconNames = Object.keys(icons) as IconName[]
